dist: xenial

language: php

php:
  - 7.3

cache:
  directories:
    - $HOME/.cache/composer

branches:
  only:
    - master

before_script:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Read-only OAuth token to work around GitHub API rate limits
  - composer config -g github-oauth.github.com "4b3b0a83ea27d9544d3608a384c7a14625a98804"

  - composer update --no-suggest --prefer-dist

script:
  - composer validate --strict
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.xml --colors=always

notifications:
  email: false

git:
  depth: 1

# send coverage to codecov.io
after_success:
  - if [ "$COVERAGE" != "" ] ; then bash <(curl -s https://codecov.io/bash) -F $COVERAGE ; fi
